### ISSUE TITLE
"smt init" fails with latest master

### ISSUE THREAD

**Issue by apdavison** [open-research/sumatra#198]
With latest master a simple "smt init" fails (this also appears to be the cause for the [broken CI runs](https://qa.nest-initiative.org/view/Sumatra/job/sumatra/203/testReport/)) . A traceback is included below. AFAICS the faulty commit is in rev. 946a4df , and the reason for the error is that the argument `path` which is passed to `os.path.realpath` has value `None` (see [line 33 in sumatra/versioncontrol/_subversion.py](https://bitbucket.org/apdavison/sumatra/commits/946a4df899e533d226fd5beb5e69b64747a64ba6#Lsumatra/versioncontrol/_subversion.pyT33))

```
Traceback (most recent call last):
  File "/home/albert/code/sumatra/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/home/albert/code/sumatra/sumatra/commands.py", line 158, in init 
    repository = get_working_copy().repository  # if no repository is specified, we assume there is a working copy in the current directory.
  File "/home/albert/code/sumatra/sumatra/versioncontrol/__init__.py", line 79, in get_working_copy
    wc = working_copy_type(path)
  File "/home/albert/code/sumatra/sumatra/versioncontrol/_subversion.py", line 33, in __init__
    self.path = os.path.realpath(path)
  File "/usr/lib/python2.7/posixpath.py", line 382, in realpath
    path, ok = _joinrealpath('', filename, {})
  File "/usr/lib/python2.7/posixpath.py", line 388, in _joinrealpath
    if isabs(rest):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```
        

 _Imported from Bitbucket issue [212](https://bitbucket.org/apdavison/sumatra/issue/212),  created by cilix on 08-30-2014 at 00:44, last modified: 08-30-2014 at 00:44_

**Comment by maxalbert** [comment]
This seems to be fixed.

**Comment by apdavison** [comment]
You should now be able to close it. I've given write access to open-research/sumatra to @maxalbert @wd15 @Felix11H (generally people who have made several pull requests, been active in the Google group or the issue tracker, etc.)

**Comment by maxalbert** [comment]
Thanks!
