### ISSUE TITLE
Fresh install results in AppRegistryNotReady

### ISSUE THREAD

**Issue by dmyersturnbull** [open-research/sumatra#226]
On Mac OS X Yosemite, I installed Sumatra using pip install sumatra and pip install GitPython==0.3.6. (Using GitPython 1.0.0 didn't work, so I can submit another issue for that.)

After running smt init, running smt list or smt run results in this stack trace:
```
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/usr/local/lib/python2.7/site-packages/sumatra/commands.py", line 370, in run
    version=args.version or 'current')
  File "/usr/local/lib/python2.7/site-packages/sumatra/projects.py", line 200, in launch
    self.add_record(record)
  File "/usr/local/lib/python2.7/site-packages/sumatra/projects.py", line 239, in add_record
    self.record_store.save(self.name, record)
  File "/usr/local/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 187, in save
    db_record = self._get_db_record(project_name, record)
  File "/usr/local/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 156, in _get_db_record
    models = self._get_models()
  File "/usr/local/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 136, in _get_models
    db_config.configure()
  File "/usr/local/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 101, in configure
    self._create_databases()
  File "/usr/local/lib/python2.7/site-packages/sumatra/recordstore/django_store/__init__.py", line 92, in _create_databases
    management.call_command('syncdb', database=label, verbosity=0)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 92, in call_command
    app_name = get_commands()[name]
  File "/usr/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 72, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
```

I'm not familiar with Django and wasn't planning to use the web interface. The documentation suggests that Django is optional. However, I also tried running django-admin startproject, but smt commands still result in the same stack trace.

**Comment by ashander** [comment]
There's another issue on this. For now, a fix is to downgrade to Django 1.6

**Comment by maxalbert** [comment]
Which version of Django are you using? I believe that the latest stable version of Sumatra (v0.6) requires Django 1.5, whereas the development version requires 1.6 (but neither will work with the latest Django). We should really have a runtime check in Sumatra which warns the user if a different version is installed, rather than waiting for Django to crash with a cryptic error like this...

**Comment by dmyersturnbull** [comment]
Thanks. Reinstalling Django with version 1.6 seemed to fix the issue.

In addition to a runtime check as @maxalbert pointed out, Sumatra should install Django 1.6 if that's the latest it can work with. Running pip install sumatra installed Django 1.8; I didn't have Django before that.
```
install_requires = ['Django>=1.4', 'django-tagging', 'httplib2',
                        'docutils', 'jinja2', 'parameters'],
```
Change to:
```
install_requires = ['Django>=1.4, <= 1.6', 'django-tagging', 'httplib2',
                        'docutils', 'jinja2', 'parameters'],
```

**Comment by ashander** [comment]
Good patch for this pip install issue, which is rasied in #199

**Comment by ashander** [comment]
PS @dmyersturnbull does GitPython==0.3.6 work for you after changing the django version? 

I have no issues w/ git on fresh install w/ python 2.7.6 but my OS env differs from yours.

```sh
$pip freeze
Django==1.6
GitPython==1.0.0
Jinja2==2.7.3
MarkupSafe==0.23
Sumatra==0.7dev
django-tagging==0.3.4
docutils==0.12
gitdb==0.6.4
httplib2==0.9
mercurial==3.3.3
parameters==0.2.1
simplejson==3.6.5
smmap==0.9.0
wsgiref==0.1.2
```

**Comment by maxalbert** [comment]
For the record: the merged fix now also raises a runtime error if the Django version is wrong:

    pkg_resources.DistributionNotFound: Django>=1.4,<=1.6
