### ISSUE TITLE
pip install sumatra - No such file or directory: 'README.rst'

### ISSUE THREAD

**Issue by tompfeil** [open-research/sumatra#266]
running `pip install sumatra` fails with the following error message on Debian 7.7 and Debian testing:

```
Downloading/unpacking sumatra
  Running setup.py egg_info for package sumatra
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "somepath/build/sumatra/setup.py", line 54, in <module>
        long_description = open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "somepath/build/sumatra/setup.py", line 54, in <module>

    long_description = open('README.rst').read(),

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in somepath/build/sumatra
Storing complete log in somepath/.pip/pip.log
```

**Comment by apdavison** [comment]
whoops, that's embarrassing. I've just released 0.7.1 [8cb30ad] which should fix this.
