### ISSUE TITLE
smt init fails if yaml is not defined

### ISSUE THREAD

**Issue by SmokinCaterpillar** [open-research/sumatra#269]
Running `smt init` fails with the following error:

    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/test-environment/bin/smt", line 7, in <module>
    from sumatra import commands, __version__
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/commands.py", line 24, in <module>
    from sumatra.projects import Project, load_project
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/projects.py", line 47, in <module>
    from sumatra.recordstore import DefaultRecordStore
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/recordstore/__init__.py", line 19, in <module>
    from . import serialization
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/recordstore/serialization.py", line 13, in <module>
    from sumatra import programs, launch, datastore, versioncontrol, parameters, dependency_finder
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/parameters.py", line 62, in <module>
    class ParameterSet(with_metaclass(abc.ABCMeta, object)):
      File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/sumatra/parameters.py", line 66, in ParameterSet
    casts = (yaml.load, )  # good behavior for all bool, at cost of dependency
    NameError: name 'yaml' is not defined

Looking into the source code I figured that in `ParameterSet` `casts=(yaml.load)` is executed without checking if `yaml_loaded` is `True`.

**Comment by livia-b** [comment]
I just experienced the same problem, I had to manually install pyYAML (I guess it's not in the dependences)

**Comment by Felix11H** [comment]
Can confirm both problem and solution.

   pip install pyyaml

did the trick.

**Comment by SmokinCaterpillar** [comment]
Yes, thanks, `pip install pyyaml` did the trick. But I guess this should only be a workaround.
Otherwise the whole try catch block in `sumatra.parameters`
   
     try:
        import yaml
        yaml_loaded = True
    except ImportError:
        yaml_loaded = False

doesn't make much sense :-)

**Comment by apdavison** [comment]
Fixed in master in 7f7f0a1 and in the 0.7 branch in 82361cf
