### ISSUE TITLE
Unable to run sumatra  for matlab scripts

### ISSUE THREAD

**Issue by mnarayan** [open-research/sumatra#283]
I have sumatra 0.7 installed on Mac OS Yosemite and Matlab 2015a.  When I configure and run smt, 

```
smt configure -e matlab -m main.m --labelgenerator timestamp

smt run -r "Testing continuity of metric for covariance matrices" --tag bc_metric

```

I get the following error. 

```
Record label for this run: '20150813-160207'
Data keys are [Discontinuity_Example1.fig(a5370a70271acd24ee0cb6a187a898abea2131c2 [2015-08-13 16:06:58]), Discontinuity_Example2.fig(9b7a8a14ad3b5d0d149d540b9987c1a783bd2e07 [2015-08-13 16:07:10])]
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/Library/Python/2.7/site-packages/sumatra/commands.py", line 392, in run
    version=args.version or 'current')
  File "/Library/Python/2.7/site-packages/sumatra/projects.py", line 219, in launch
    record.register(record.repository.get_working_copy())
  File "/Library/Python/2.7/site-packages/sumatra/records.py", line 113, in register
    self.dependencies = dependency_finder.find_dependencies(self.main_file, self.executable)
  File "/Library/Python/2.7/site-packages/sumatra/dependency_finder/__init__.py", line 35, in find_dependencies
    return matlab.find_dependencies(filename, executable)
  File "/Library/Python/2.7/site-packages/sumatra/dependency_finder/matlab.py", line 39, in find_dependencies
    file_data = (open('depfun.data', 'r'))
IOError: [Errno 2] No such file or directory: u'depfun.data'
```

I also noticed that instead of calling matlab in nodesktop mode, this approach actually calls matlab in full desktop mode and then fails to run the main function. 

I've had similar experiences when running similar experiments using matlab on linux platforms as well.

**Comment by apdavison** [comment]
Is this related to #140?

The person who originally added MATLAB support no longer contributes to the project. I don't have a copy of MATLAB myself, but I will try to get one so I can fix this.
