### ISSUE TITLE
Using --addlabel=parameters raises TypeError("can't intern subclass of string") in python 2.7

### ISSUE THREAD

**Issue by maxalbert** [open-research/sumatra#287]
Commit 124a113841f2 (which contained the fix for #278) introduced a new bug when using the option `--addlabel=parameters`.

To reproduce:

```
git clone https://github.com/maxalbert/smt_bug.git
cd smt_bug
smt init TestProject
smt configure -e python -m main.py --addlabel=parameters
smt run -r "Test run"
```

This results in the following traceback. (However, if you omit the option `--addlabel=parameters` in the `smt configure` command above then it works fine.)

```
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/home/vagrant/work/code/sumatra/sumatra/commands.py", line 401, in run
    version=args.version or 'current')
  File "/home/vagrant/work/code/sumatra/sumatra/projects.py", line 217, in launch
    record.run(with_label=self.data_label)
  File "/home/vagrant/work/code/sumatra/sumatra/records.py", line 146, in run
    self.datastore.root = join(self.datastore.root, self.label)
  File "/home/vagrant/work/code/sumatra/sumatra/datastore/filesystem.py", line 91, in __set_root
    path = Path(value)
  File "/usr/local/lib/python2.7/dist-packages/pathlib.py", line 936, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/lib/python2.7/dist-packages/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python2.7/dist-packages/pathlib.py", line 606, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/local/lib/python2.7/dist-packages/pathlib.py", line 90, in parse_parts
    parsed.append(intern(x))
TypeError: can't intern subclass of string
```

I'm using Python 2.7.6 on Ubuntu 14.04 with the latest Sumatra master (f5f96ba842f031). I haven't had a chance to test it on Python 3 yet.

**Comment by timtroendle** [comment]
Without having tested it, I assume this is a Py2 problem only. ``new_str`` from ``python-future`` and ``Path`` from ``pathlib`` don't seem to work with each other -- which is quite unfortunate. The best solution I could come up with here would be not to use ``pathlib`` in ``sumatra.datastore.filesystem``; not smart, but should do the work.

**Comment by maxalbert** [comment]
Yes, you are right regarding Py3. I did a test with it earlier and it does work.

The problem arises because the datastore root is set to a `newstr` instead of `str` or `unicode`. I think the least intrusive way of fixing it is inside `FileSystemDataStore.__set_root` where we can check simply convert the argument `value` to one of those types if needed (which is only necessary for Python2). I'll submit a PR for this tomorrow.
