### ISSUE TITLE
Sumatra fails when importing non standard libray

### ISSUE THREAD

**Issue by timtammittee** [open-research/sumatra#296]
I'm having problems with Sumatra when trying to run any file that imports a non standart library.
Sumatra is version 0.7.3 installed using pip

smt run fails with the following output:
```
Using /usr/bin/python
Using /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/smt", line 31, in <module>
    main(sys.argv[2:])
  File "/usr/local/lib/python2.7/dist-packages/sumatra/commands.py", line 401, in run
    version=args.version or 'current')
  File "/usr/local/lib/python2.7/dist-packages/sumatra/projects.py", line 216, in launch
    launch_mode, label, reason, timestamp_format)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/projects.py", line 206, in new_record
    record.register(working_copy)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/records.py", line 113, in register
    self.dependencies = dependency_finder.find_dependencies(self.main_file, self.executable)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/dependency_finder/__init__.py", line 37, in find_dependencies
    return python.find_dependencies(filename, executable)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/dependency_finder/python.py", line 227, in find_dependencies
    return core.find_versions(dependencies, heuristics)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/dependency_finder/core.py", line 65, in find_versions
    dependencies = heuristic(dependencies)
  File "/usr/local/lib/python2.7/dist-packages/sumatra/dependency_finder/core.py", line 42, in find_versions_from_versioncontrol
    dependency.version = wc.current_version()
  File "/usr/local/lib/python2.7/dist-packages/sumatra/versioncontrol/_git.py", line 80, in current_version
    return head.commit.hexsha
  File "/usr/local/lib/python2.7/dist-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/usr/local/lib/python2.7/dist-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/local/lib/python2.7/dist-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/usr/local/lib/python2.7/dist-packages/git/refs/symbolic.py", line 157, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```
(An older version of this issue said that there is an error importing numpy but i've found out that the error appears with any non standart library)

**Comment by apdavison** [comment]
Is your "non-standard" library under version control with Git? If so, what is the currently checked-out branch, and what branches exist?

**Comment by apdavison** [comment]
@timtammittee I don't have enough information to reproduce this. Please can you reply to my questions from Sept 21st?

**Comment by timtammittee** [comment]
I'm sorry, I was a bit busy with work but I'll look back into it the next
few days.
Am 02.01.2016 11:33 schrieb "Andrew Davison" <notifications@github.com>:

**Comment by timtammittee** [comment]
Ok, had finally had a look at it again and could not reproduce it. 

i guess this issue can be closed

**Comment by maxalbert** [comment]
Thanks for looking at this again! Feel free to re-open the issue if you encounter the problem again (ideally with precise steps how to reproduce it).
