### ISSUE TITLE
run yield AttributeError

### ISSUE THREAD

**Issue by dacoex** [open-research/sumatra#349]
after successfulling settign teh repo & project up (see #347 ), there is another issue:

```
(C:\Users\%USER%\AppData\Local\Continuum\Anaconda3) C:\Users\%USER%\Documents\devel\python\sumatra_trials\sumatra_test_proj\sumatra_trial>python C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\Scripts\smt ru
n --main=src\models\test_smt.py -e "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\python.exe"
Traceback (most recent call last):
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\Scripts\smt", line 31, in <module>
    main(sys.argv[2:])
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumatra\commands.py", line 382, in run
    executable = get_executable(path=executable_path)
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumatra\programs.py", line 232, in get_executable
    program = Executable(path)
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumatra\programs.py", line 81, in __init__
    self.version = version or self._get_version()
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumatra\programs.py", line 109, in _get_version
    shell=True, timeout=5)
  File "C:\Users\%USER%\AppData\Local\Continuum\Anaconda3\lib\site-packages\sumatra\core.py", line 69, in run
    signal.signal(signal.SIGALRM, alarm_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'

(C:\Users\%USER%\AppData\Local\Continuum\Anaconda3) C:\Users\%USER%\Documents\devel\python\sumatra_trials\sumatra_test_proj\sumatra_trial>
```

What could be the reason for this failure?

**Comment by dacoex** [comment]
With the [sumatra_execise](https://bitbucket.org/apdavison/ircr2013), this does not appear.

**Comment by timtroendle** [comment]
This issue is a duplicate of #189. You will find further explanations over there.

**Comment by dacoex** [comment]
Sorry, then I close here.
